### ISSUE TITLE
Getting Method ReflectionParameter::getClass() is deprecated on PHP 8.0.3

### ISSUE THREAD

**Issue by lemonlover** [jkocik/laravel-profiler#10]
Hi, getting server error while using this package on PHP 8.0.3 in HttpRoute.php on line 130

It's fixed by 

```
$formRequest = Collection::make($parameters)->filter(function (ReflectionParameter $parameter) {
  return $parameter->getDeclaringClass() && $parameter->getDeclaringClass()->isSubclassOf(FormRequest::class);
})->first();
```

Hope this will be fixed in later updates. 

Thanks for your attention :)

**Comment by jkocik** [comment]
Hi,

Thanks for the suggestion! 2.0.3 solves the issue.
