### ISSUE TITLE
No API Calls Captured on the Local Machine

### ISSUE THREAD

**Issue by shivdhwaj** [jkocik/laravel-profiler#6]
Server and client are working fine
Commands are captured well 
When I try to hit the existing API endpoint with the relevant port all it says is 404 Not Found

Working the same API and Code with `php artisan serve`, but failing with `php artisan profiler:server`

**Comment by jkocik** [comment]
If you can see your commands execution in Profiler Client you should see any other framework activity. There is no difference between commands and requests - Profiler processes them the same way. Can you share your profiler's configuration and can you give some more details about 404 issue?
