### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by castorinop** [jkocik/laravel-profiler#7]
i have a exception but not catch by the profiler. 
Maybe need a special php config ?
```
Caused by
PDOException: SQLSTATE[22003]:

```

**Comment by jkocik** [comment]
Hi,

Profiler checkes what is catched by Laravel Exception Handler. Does Laravel report that exception and Profiler does not?

**Comment by castorinop** [comment]
Works well. 

dont catch exceptions when runing phpunit tests.
