### ISSUE TITLE
Client returns 404

### ISSUE THREAD

**Issue by LearningRaph** [jkocik/laravel-profiler#8]
Hi,

I'm on laravel 8 with a fresh install of laravel-profiler and client on windows and when I npm run pc, it opens a browser tab with a 404 error "Cannot GET /".  HTTP and socket port have been correctly defined in profiler config file.

Any idea on how to deal with this ?

Thanks

**Comment by jkocik** [comment]
Hi,

Modify profiler-client script like so:

`"profiler-client": "http-server node_modules/laravel-profiler-client/dist/",`

and try again.

**Comment by LearningRaph** [comment]
It launches on 8081 with a ERR_INVALID_REDIRECT and when I get him back on 8080 I still get the "Cannot GET /"...

**Comment by jkocik** [comment]
I don't have Windows to try it now, but it looks like this is http-server package issue. Try to add /index.html at the end of url you try to open in your browser. If this does not work check this: https://github.com/http-party/http-server/issues/525

**Comment by LearningRaph** [comment]
Got it working ! Thanks 👍

**Comment by hardik-gajera** [comment]
Thank after adding index.html its works
